## Úloha 1 - Knihovny a moduly pro matematické výpočty


0) povinné importy

In [154]:
import numpy as np
import time as t

In [155]:
def vyhodnot(python_start, python_konec, numpy_start, numpy_konec):
    delka_python = python_konec - python_start
    delka_numpy = numpy_konec - numpy_start
    print("Python délka {:.10f} sekund.".format(delka_python))
    print("Numpy délka {:.10f} sekund.".format(delka_numpy))

1) Součet matic

In [156]:
#python
def secti_matice(matice1, matice2):
    # Zjištění rozměrů matice
    radky = len(matice1)
    sloupce = len(matice1[0])

    # Vytvoření prázdné matice pro výsledek
    vysledek = []

    # Procházení a sečtení odpovídajících prvky z obou matic
    for i in range(radky):
        nova_radek = []
        for j in range(sloupce):
            nova_radek.append(matice1[i][j] + matice2[i][j])
        vysledek.append(nova_radek)

    return vysledek

# Příklad použití
matice_A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matice_B = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

python_start = t.perf_counter()
vysledna_matice = secti_matice(matice_A, matice_B)
python_konec = t.perf_counter()
for radek in vysledna_matice:
    print(radek)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [157]:
#numpy
# Definice matic jako ndarray objektů
matice_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matice_B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Sčítání matic pomocí operátoru +
numpy_start = t.perf_counter()
vysledna_matice = matice_A + matice_B
numpy_konec = t.perf_counter()
print(vysledna_matice)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [158]:
# Vyhodnocení
vyhodnot(python_start, python_konec, numpy_start, numpy_konec)

Python délka 0.0000342000 sekund.
Numpy délka 0.0000388000 sekund.


2) Násobení matice konstantou

In [159]:
#python
def vynasob_matici_cislem(matice, konstanta):
    # Zjištění rozměrů matice
    radky = len(matice)
    sloupce = len(matice[0])

    # Vytvoření prázdné matice pro výsledek
    vysledek = []

    # Procházení každého prveku v matici a vynásobení konstantou
    for i in range(radky):
        nova_radek = []
        for j in range(sloupce):
            nova_radek.append(matice[i][j] * konstanta)
        vysledek.append(nova_radek)

    return vysledek

# Příklad použití
matice_A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
konstanta = 2
python_start = t.perf_counter()
vysledna_matice = vynasob_matici_cislem(matice_A, konstanta)
python_konec = t.perf_counter()
for radek in vysledna_matice:
    print(radek)

[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [160]:
#numpy
# Definice matice jako ndarray objektu
matice_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
konstanta = 2

# Vynásobení matice číslem
numpy_start = t.perf_counter()
vysledna_matice = matice_A * konstanta
numpy_konec = t.perf_counter()

print(vysledna_matice)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [161]:
# Vyhodnocení
vyhodnot(python_start, python_konec, numpy_start, numpy_konec)

Python délka 0.0000329000 sekund.
Numpy délka 0.0000462000 sekund.


3) Transpozice matice

In [162]:
#python
def transpozice_matice(matice):
    # Zjištění rozměrů matice
    radky = len(matice)
    sloupce = len(matice[0])

    # Vytvoření prázdné matice pro výsledek
    vysledna_matice = []

    # Procházení každého prvku matice a uhládání na nový index (prohozením indexu řádku a sloupce)
    for i in range(sloupce):
        novy_radek = []
        for j in range(radky):
            novy_radek.append(matice[j][i])
        vysledna_matice.append(novy_radek)

    return vysledna_matice

# Příklad použití
matice_A = [[1, 2, 3], [4, 5, 6]]
python_start = t.perf_counter()
vysledna_matice = transpozice_matice(matice_A)
python_konec = t.perf_counter()

for radek in vysledna_matice:
    print(radek)

[1, 4]
[2, 5]
[3, 6]


In [163]:
#numpy
# Definice matice jako ndarray objektu
matice_A = np.array([[1, 2, 3], [4, 5, 6]])

# Transpozice matice
numpy_start = t.perf_counter()
vysledna_matice = np.transpose(matice_A)
numpy_konec = t.perf_counter()

print(vysledna_matice)

[[1 4]
 [2 5]
 [3 6]]


In [164]:
# Vyhodnocení
vyhodnot(python_start, python_konec, numpy_start, numpy_konec)

Python délka 0.0000322000 sekund.
Numpy délka 0.0000405000 sekund.


4) Nalezení kořenu kvadratické rovnice

In [165]:
#python
import math

def solve_quadratic(a, b, c):
    # Výpočet diskriminantu
    discriminant = b**2 - 4*a*c

    # Podmínka pro reálná řešení
    if discriminant >= 0:
        # Výpočet dvou řešení
        x1 = (-b + math.sqrt(discriminant)) / (2*a)
        x2 = (-b - math.sqrt(discriminant)) / (2*a)
        return x1, x2
    else:
        # Diskriminant je záporný, nemá reálné řešení
        return None

# Příklad použití
a = 1
b = -3
c = 2

python_start = t.perf_counter()
res = solve_quadratic(a, b, c)
python_konec = t.perf_counter()

if res:
    x1, x2 = res
    print(f"Řešení jsou: x1 = {x1}, x2 = {x2}")
else:
    print("Kvadratická rovnice nemá reálná řešení.")

Řešení jsou: x1 = 2.0, x2 = 1.0


In [166]:
#numpy
a = 1
b = -3
c = 2

# Vytvoření koeficientů pro kvadratický polynom ax^2 + bx + c
coef = [a, b, c]

numpy_start = t.perf_counter()
roots = np.roots(coef)
numpy_konec = t.perf_counter()

if len(roots) == 2:
    x1, x2 = roots
    print(f"Řešení jsou: x1 = {x1}, x2 = {x2}")
else:
    print("Kvadratická rovnice nemá reálná řešení.")

Řešení jsou: x1 = 2.0, x2 = 1.0


In [167]:
# Vyhodnocení
vyhodnot(python_start, python_konec, numpy_start, numpy_konec)

Python délka 0.0000344000 sekund.
Numpy délka 0.0002234000 sekund.


5) Výpočet průměru prvků v matici

In [168]:
#python
def average(matrix):
    # Inicializace proměnných pro součet a počet prvků
    total_sum = 0
    count = 0

    # Procházení matice
    for row in matrix:
        for value in row:
            total_sum += value
            count += 1

    # Spočítání průměru
    if count == 0:
        return 0 
    else:
        return total_sum / count

# Příklad použití
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

python_start = t.perf_counter()
avg = average(matrix)
python_konec = t.perf_counter()

print("Průměr prvků matice:", avg)

Průměr prvků matice: 5.0


In [169]:
#numpy
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
numpy_start = t.perf_counter()
mean = np.mean(matrix)
numpy_konec = t.perf_counter()
print("Průměr prvků matice:", mean)

Průměr prvků matice: 5.0


In [170]:
# Vyhodnocení
vyhodnot(python_start, python_konec, numpy_start, numpy_konec)

Python délka 0.0000309000 sekund.
Numpy délka 0.0000852000 sekund.
